//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ServiceStandardErrorRespModel: APIModel {

    public var message: String?

    public init(message: String? = nil) {
        self.message = message
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        message = try container.decodeIfPresent("message")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(message, forKey: "message")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ServiceStandardErrorRespModel else { return false }
      guard self.message == object.message else { return false }
      return true
    }

    public static func == (lhs: ServiceStandardErrorRespModel, rhs: ServiceStandardErrorRespModel) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
