//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class V0AppRespModel: APIModel {

    public var slug: String?

    public var status: String?

    public init(slug: String? = nil, status: String? = nil) {
        self.slug = slug
        self.status = status
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        slug = try container.decodeIfPresent("slug")
        status = try container.decodeIfPresent("status")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(slug, forKey: "slug")
        try container.encodeIfPresent(status, forKey: "status")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? V0AppRespModel else { return false }
      guard self.slug == object.slug else { return false }
      guard self.status == object.status else { return false }
      return true
    }

    public static func == (lhs: V0AppRespModel, rhs: V0AppRespModel) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
