//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class V0AppConfigRespModel: APIModel {
    public static func == (lhs: V0AppConfigRespModel, rhs: V0AppConfigRespModel) -> Bool {
        return false
    }
}

