//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class V0BuildWorkflowListResponseModel: APIModel {

    public var data: [String]?

    public init(data: [String]? = nil) {
        self.data = data
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        data = try container.decodeArrayIfPresent("data")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(data, forKey: "data")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? V0BuildWorkflowListResponseModel else { return false }
      guard self.data == object.data else { return false }
      return true
    }

    public static func == (lhs: V0BuildWorkflowListResponseModel, rhs: V0BuildWorkflowListResponseModel) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
