//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class V0BuildCertificateResponseItemModel: APIModel {

    public var certificatePassword: String?

    public var downloadURL: String?

    public var isExpose: Bool?

    public var isProtected: Bool?

    public var processed: Bool?

    public var slug: String?

    public var uploadFileName: String?

    public var uploadFileSize: Int?

    public var uploadURL: String?

    public init(certificatePassword: String? = nil, downloadURL: String? = nil, isExpose: Bool? = nil, isProtected: Bool? = nil, processed: Bool? = nil, slug: String? = nil, uploadFileName: String? = nil, uploadFileSize: Int? = nil, uploadURL: String? = nil) {
        self.certificatePassword = certificatePassword
        self.downloadURL = downloadURL
        self.isExpose = isExpose
        self.isProtected = isProtected
        self.processed = processed
        self.slug = slug
        self.uploadFileName = uploadFileName
        self.uploadFileSize = uploadFileSize
        self.uploadURL = uploadURL
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        certificatePassword = try container.decodeIfPresent("certificate_password")
        downloadURL = try container.decodeIfPresent("download_url")
        isExpose = try container.decodeIfPresent("is_expose")
        isProtected = try container.decodeIfPresent("is_protected")
        processed = try container.decodeIfPresent("processed")
        slug = try container.decodeIfPresent("slug")
        uploadFileName = try container.decodeIfPresent("upload_file_name")
        uploadFileSize = try container.decodeIfPresent("upload_file_size")
        uploadURL = try container.decodeIfPresent("upload_url")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(certificatePassword, forKey: "certificate_password")
        try container.encodeIfPresent(downloadURL, forKey: "download_url")
        try container.encodeIfPresent(isExpose, forKey: "is_expose")
        try container.encodeIfPresent(isProtected, forKey: "is_protected")
        try container.encodeIfPresent(processed, forKey: "processed")
        try container.encodeIfPresent(slug, forKey: "slug")
        try container.encodeIfPresent(uploadFileName, forKey: "upload_file_name")
        try container.encodeIfPresent(uploadFileSize, forKey: "upload_file_size")
        try container.encodeIfPresent(uploadURL, forKey: "upload_url")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? V0BuildCertificateResponseItemModel else { return false }
      guard self.certificatePassword == object.certificatePassword else { return false }
      guard self.downloadURL == object.downloadURL else { return false }
      guard self.isExpose == object.isExpose else { return false }
      guard self.isProtected == object.isProtected else { return false }
      guard self.processed == object.processed else { return false }
      guard self.slug == object.slug else { return false }
      guard self.uploadFileName == object.uploadFileName else { return false }
      guard self.uploadFileSize == object.uploadFileSize else { return false }
      guard self.uploadURL == object.uploadURL else { return false }
      return true
    }

    public static func == (lhs: V0BuildCertificateResponseItemModel, rhs: V0BuildCertificateResponseItemModel) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
