//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class V0BuildLogChunkItemResponseModel: APIModel {

    public var chunk: String?

    public var position: Int?

    public init(chunk: String? = nil, position: Int? = nil) {
        self.chunk = chunk
        self.position = position
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        chunk = try container.decodeIfPresent("chunk")
        position = try container.decodeIfPresent("position")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(chunk, forKey: "chunk")
        try container.encodeIfPresent(position, forKey: "position")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? V0BuildLogChunkItemResponseModel else { return false }
      guard self.chunk == object.chunk else { return false }
      guard self.position == object.position else { return false }
      return true
    }

    public static func == (lhs: V0BuildLogChunkItemResponseModel, rhs: V0BuildLogChunkItemResponseModel) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
