//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class V0BuildTriggerParamsBuildParams: APIModel {

    public var branch: String?

    public var branchDest: String?

    public var branchDestRepoOwner: String?

    public var branchRepoOwner: String?

    public var buildRequestSlug: String?

    public var commitHash: String?

    public var commitMessage: String?

    public var commitPaths: [V0CommitPaths]?

    public var diffURL: String?

    public var environments: [V0BuildParamsEnvironment]?

    public var pullRequestAuthor: String?

    public var pullRequestHeadBranch: String?

    public var pullRequestId: [String: Any]?

    public var pullRequestMergeBranch: String?

    public var pullRequestRepositoryURL: String?

    public var skipGitStatusReport: Bool?

    public var tag: String?

    public var workflowId: String?

    public init(branch: String? = nil, branchDest: String? = nil, branchDestRepoOwner: String? = nil, branchRepoOwner: String? = nil, buildRequestSlug: String? = nil, commitHash: String? = nil, commitMessage: String? = nil, commitPaths: [V0CommitPaths]? = nil, diffURL: String? = nil, environments: [V0BuildParamsEnvironment]? = nil, pullRequestAuthor: String? = nil, pullRequestHeadBranch: String? = nil, pullRequestId: [String: Any]? = nil, pullRequestMergeBranch: String? = nil, pullRequestRepositoryURL: String? = nil, skipGitStatusReport: Bool? = nil, tag: String? = nil, workflowId: String? = nil) {
        self.branch = branch
        self.branchDest = branchDest
        self.branchDestRepoOwner = branchDestRepoOwner
        self.branchRepoOwner = branchRepoOwner
        self.buildRequestSlug = buildRequestSlug
        self.commitHash = commitHash
        self.commitMessage = commitMessage
        self.commitPaths = commitPaths
        self.diffURL = diffURL
        self.environments = environments
        self.pullRequestAuthor = pullRequestAuthor
        self.pullRequestHeadBranch = pullRequestHeadBranch
        self.pullRequestId = pullRequestId
        self.pullRequestMergeBranch = pullRequestMergeBranch
        self.pullRequestRepositoryURL = pullRequestRepositoryURL
        self.skipGitStatusReport = skipGitStatusReport
        self.tag = tag
        self.workflowId = workflowId
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        branch = try container.decodeIfPresent("branch")
        branchDest = try container.decodeIfPresent("branch_dest")
        branchDestRepoOwner = try container.decodeIfPresent("branch_dest_repo_owner")
        branchRepoOwner = try container.decodeIfPresent("branch_repo_owner")
        buildRequestSlug = try container.decodeIfPresent("build_request_slug")
        commitHash = try container.decodeIfPresent("commit_hash")
        commitMessage = try container.decodeIfPresent("commit_message")
        commitPaths = try container.decodeArrayIfPresent("commit_paths")
        diffURL = try container.decodeIfPresent("diff_url")
        environments = try container.decodeArrayIfPresent("environments")
        pullRequestAuthor = try container.decodeIfPresent("pull_request_author")
        pullRequestHeadBranch = try container.decodeIfPresent("pull_request_head_branch")
        pullRequestId = try container.decodeAnyIfPresent("pull_request_id")
        pullRequestMergeBranch = try container.decodeIfPresent("pull_request_merge_branch")
        pullRequestRepositoryURL = try container.decodeIfPresent("pull_request_repository_url")
        skipGitStatusReport = try container.decodeIfPresent("skip_git_status_report")
        tag = try container.decodeIfPresent("tag")
        workflowId = try container.decodeIfPresent("workflow_id")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(branch, forKey: "branch")
        try container.encodeIfPresent(branchDest, forKey: "branch_dest")
        try container.encodeIfPresent(branchDestRepoOwner, forKey: "branch_dest_repo_owner")
        try container.encodeIfPresent(branchRepoOwner, forKey: "branch_repo_owner")
        try container.encodeIfPresent(buildRequestSlug, forKey: "build_request_slug")
        try container.encodeIfPresent(commitHash, forKey: "commit_hash")
        try container.encodeIfPresent(commitMessage, forKey: "commit_message")
        try container.encodeIfPresent(commitPaths, forKey: "commit_paths")
        try container.encodeIfPresent(diffURL, forKey: "diff_url")
        try container.encodeIfPresent(environments, forKey: "environments")
        try container.encodeIfPresent(pullRequestAuthor, forKey: "pull_request_author")
        try container.encodeIfPresent(pullRequestHeadBranch, forKey: "pull_request_head_branch")
        try container.encodeAnyIfPresent(pullRequestId, forKey: "pull_request_id")
        try container.encodeIfPresent(pullRequestMergeBranch, forKey: "pull_request_merge_branch")
        try container.encodeIfPresent(pullRequestRepositoryURL, forKey: "pull_request_repository_url")
        try container.encodeIfPresent(skipGitStatusReport, forKey: "skip_git_status_report")
        try container.encodeIfPresent(tag, forKey: "tag")
        try container.encodeIfPresent(workflowId, forKey: "workflow_id")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? V0BuildTriggerParamsBuildParams else { return false }
      guard self.branch == object.branch else { return false }
      guard self.branchDest == object.branchDest else { return false }
      guard self.branchDestRepoOwner == object.branchDestRepoOwner else { return false }
      guard self.branchRepoOwner == object.branchRepoOwner else { return false }
      guard self.buildRequestSlug == object.buildRequestSlug else { return false }
      guard self.commitHash == object.commitHash else { return false }
      guard self.commitMessage == object.commitMessage else { return false }
      guard self.commitPaths == object.commitPaths else { return false }
      guard self.diffURL == object.diffURL else { return false }
      guard self.environments == object.environments else { return false }
      guard self.pullRequestAuthor == object.pullRequestAuthor else { return false }
      guard self.pullRequestHeadBranch == object.pullRequestHeadBranch else { return false }
      guard NSDictionary(dictionary: self.pullRequestId ?? [:]).isEqual(to: object.pullRequestId ?? [:]) else { return false }
      guard self.pullRequestMergeBranch == object.pullRequestMergeBranch else { return false }
      guard self.pullRequestRepositoryURL == object.pullRequestRepositoryURL else { return false }
      guard self.skipGitStatusReport == object.skipGitStatusReport else { return false }
      guard self.tag == object.tag else { return false }
      guard self.workflowId == object.workflowId else { return false }
      return true
    }

    public static func == (lhs: V0BuildTriggerParamsBuildParams, rhs: V0BuildTriggerParamsBuildParams) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
