//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class V0CommitPaths: APIModel {

    public var added: [String]?

    public var modified: [String]?

    public var removed: [String]?

    public init(added: [String]? = nil, modified: [String]? = nil, removed: [String]? = nil) {
        self.added = added
        self.modified = modified
        self.removed = removed
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        added = try container.decodeArrayIfPresent("added")
        modified = try container.decodeArrayIfPresent("modified")
        removed = try container.decodeArrayIfPresent("removed")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(added, forKey: "added")
        try container.encodeIfPresent(modified, forKey: "modified")
        try container.encodeIfPresent(removed, forKey: "removed")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? V0CommitPaths else { return false }
      guard self.added == object.added else { return false }
      guard self.modified == object.modified else { return false }
      guard self.removed == object.removed else { return false }
      return true
    }

    public static func == (lhs: V0CommitPaths, rhs: V0CommitPaths) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
