//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class V0FindAvatarCandidateResponseItem: APIModel {

    public var downloadURL: String?

    public var filename: String?

    public var slug: String?

    public init(downloadURL: String? = nil, filename: String? = nil, slug: String? = nil) {
        self.downloadURL = downloadURL
        self.filename = filename
        self.slug = slug
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        downloadURL = try container.decodeIfPresent("download_url")
        filename = try container.decodeIfPresent("filename")
        slug = try container.decodeIfPresent("slug")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(downloadURL, forKey: "download_url")
        try container.encodeIfPresent(filename, forKey: "filename")
        try container.encodeIfPresent(slug, forKey: "slug")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? V0FindAvatarCandidateResponseItem else { return false }
      guard self.downloadURL == object.downloadURL else { return false }
      guard self.filename == object.filename else { return false }
      guard self.slug == object.slug else { return false }
      return true
    }

    public static func == (lhs: V0FindAvatarCandidateResponseItem, rhs: V0FindAvatarCandidateResponseItem) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
