//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class V0OrganizationDataModel: APIModel {

    public var avatarIconURL: String?

    public var concurrencyCount: Int?

    public var name: String?

    public var owners: [V0OrganizationOwner]?

    public var slug: String?

    public init(avatarIconURL: String? = nil, concurrencyCount: Int? = nil, name: String? = nil, owners: [V0OrganizationOwner]? = nil, slug: String? = nil) {
        self.avatarIconURL = avatarIconURL
        self.concurrencyCount = concurrencyCount
        self.name = name
        self.owners = owners
        self.slug = slug
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        avatarIconURL = try container.decodeIfPresent("avatar_icon_url")
        concurrencyCount = try container.decodeIfPresent("concurrency_count")
        name = try container.decodeIfPresent("name")
        owners = try container.decodeArrayIfPresent("owners")
        slug = try container.decodeIfPresent("slug")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(avatarIconURL, forKey: "avatar_icon_url")
        try container.encodeIfPresent(concurrencyCount, forKey: "concurrency_count")
        try container.encodeIfPresent(name, forKey: "name")
        try container.encodeIfPresent(owners, forKey: "owners")
        try container.encodeIfPresent(slug, forKey: "slug")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? V0OrganizationDataModel else { return false }
      guard self.avatarIconURL == object.avatarIconURL else { return false }
      guard self.concurrencyCount == object.concurrencyCount else { return false }
      guard self.name == object.name else { return false }
      guard self.owners == object.owners else { return false }
      guard self.slug == object.slug else { return false }
      return true
    }

    public static func == (lhs: V0OrganizationDataModel, rhs: V0OrganizationDataModel) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
