//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class V0OwnerAccountResponseModel: APIModel {

    public var accountType: String?

    public var name: String?

    public var slug: String?

    public init(accountType: String? = nil, name: String? = nil, slug: String? = nil) {
        self.accountType = accountType
        self.name = name
        self.slug = slug
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        accountType = try container.decodeIfPresent("account_type")
        name = try container.decodeIfPresent("name")
        slug = try container.decodeIfPresent("slug")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(accountType, forKey: "account_type")
        try container.encodeIfPresent(name, forKey: "name")
        try container.encodeIfPresent(slug, forKey: "slug")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? V0OwnerAccountResponseModel else { return false }
      guard self.accountType == object.accountType else { return false }
      guard self.name == object.name else { return false }
      guard self.slug == object.slug else { return false }
      return true
    }

    public static func == (lhs: V0OwnerAccountResponseModel, rhs: V0OwnerAccountResponseModel) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
