//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class V0PlanDataModel: APIModel {

    public var containerCount: Int?

    public var expiresAt: String?

    public var id: String?

    public var name: String?

    public var price: Int?

    public init(containerCount: Int? = nil, expiresAt: String? = nil, id: String? = nil, name: String? = nil, price: Int? = nil) {
        self.containerCount = containerCount
        self.expiresAt = expiresAt
        self.id = id
        self.name = name
        self.price = price
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        containerCount = try container.decodeIfPresent("container_count")
        expiresAt = try container.decodeIfPresent("expires_at")
        id = try container.decodeIfPresent("id")
        name = try container.decodeIfPresent("name")
        price = try container.decodeIfPresent("price")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(containerCount, forKey: "container_count")
        try container.encodeIfPresent(expiresAt, forKey: "expires_at")
        try container.encodeIfPresent(id, forKey: "id")
        try container.encodeIfPresent(name, forKey: "name")
        try container.encodeIfPresent(price, forKey: "price")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? V0PlanDataModel else { return false }
      guard self.containerCount == object.containerCount else { return false }
      guard self.expiresAt == object.expiresAt else { return false }
      guard self.id == object.id else { return false }
      guard self.name == object.name else { return false }
      guard self.price == object.price else { return false }
      return true
    }

    public static func == (lhs: V0PlanDataModel, rhs: V0PlanDataModel) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
