//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class V0ProvProfileDocumentUpdateParams: APIModel {

    public var isExpose: Bool?

    public var isProtected: Bool?

    public var processed: Bool?

    public init(isExpose: Bool? = nil, isProtected: Bool? = nil, processed: Bool? = nil) {
        self.isExpose = isExpose
        self.isProtected = isProtected
        self.processed = processed
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        isExpose = try container.decodeIfPresent("is_expose")
        isProtected = try container.decodeIfPresent("is_protected")
        processed = try container.decodeIfPresent("processed")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(isExpose, forKey: "is_expose")
        try container.encodeIfPresent(isProtected, forKey: "is_protected")
        try container.encodeIfPresent(processed, forKey: "processed")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? V0ProvProfileDocumentUpdateParams else { return false }
      guard self.isExpose == object.isExpose else { return false }
      guard self.isProtected == object.isProtected else { return false }
      guard self.processed == object.processed else { return false }
      return true
    }

    public static func == (lhs: V0ProvProfileDocumentUpdateParams, rhs: V0ProvProfileDocumentUpdateParams) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
