//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class V0UserProfileDataModel: APIModel {

    public var avatarURL: String?

    public var email: String?

    public var slug: String?

    public var unconfirmedEmail: String?

    public var username: String?

    public init(avatarURL: String? = nil, email: String? = nil, slug: String? = nil, unconfirmedEmail: String? = nil, username: String? = nil) {
        self.avatarURL = avatarURL
        self.email = email
        self.slug = slug
        self.unconfirmedEmail = unconfirmedEmail
        self.username = username
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        avatarURL = try container.decodeIfPresent("avatar_url")
        email = try container.decodeIfPresent("email")
        slug = try container.decodeIfPresent("slug")
        unconfirmedEmail = try container.decodeIfPresent("unconfirmed_email")
        username = try container.decodeIfPresent("username")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(avatarURL, forKey: "avatar_url")
        try container.encodeIfPresent(email, forKey: "email")
        try container.encodeIfPresent(slug, forKey: "slug")
        try container.encodeIfPresent(unconfirmedEmail, forKey: "unconfirmed_email")
        try container.encodeIfPresent(username, forKey: "username")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? V0UserProfileDataModel else { return false }
      guard self.avatarURL == object.avatarURL else { return false }
      guard self.email == object.email else { return false }
      guard self.slug == object.slug else { return false }
      guard self.unconfirmedEmail == object.unconfirmedEmail else { return false }
      guard self.username == object.username else { return false }
      return true
    }

    public static func == (lhs: V0UserProfileDataModel, rhs: V0UserProfileDataModel) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
